% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Preprocessing},
  pdfauthor={Eva},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Preprocessing}
\author{Eva}
\date{4/3/2020}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{clean-ws-set-wd}{%
\section{clean WS, set WD}\label{clean-ws-set-wd}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(}\DataTypeTok{list =} \KeywordTok{ls}\NormalTok{());}
\end{Highlighting}
\end{Shaded}

Set your local working directory. This should be (and is assumed to be
in the rest of the code) the highest point in your local folder:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{localGitDir <-}\StringTok{ 'C:/Users/eva_v/Documents/GitHub/leverhulmeNDL'}
\CommentTok{#setwd(localGitDir);}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fribbleSet <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\KeywordTok{paste}\NormalTok{(localGitDir, }\StringTok{"/exp1/stimuli/stimuli.csv"}\NormalTok{, }\DataTypeTok{sep =} \StringTok{""}\NormalTok{), }
                       \DataTypeTok{header =}\NormalTok{ T,}
                       \DataTypeTok{colClasses=}\KeywordTok{c}\NormalTok{(}\StringTok{"cueID"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"bodyShape"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"label"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"fribbleID"}\NormalTok{=}\StringTok{"factor"}
\NormalTok{                        ));}
\end{Highlighting}
\end{Shaded}

\hypertarget{check-stimuli-set}{%
\section{Check stimuli set}\label{check-stimuli-set}}

It's important to check that every fribble is unique in the way its
features are assembled within each category. Feature position and
identity are coded into cueID.

I'm going to check whether the combination of cues used to build the
fribble is unique by filtering for n \textgreater{} 1:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fribbleSet }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(category, cueID) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{>}\StringTok{ }\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Factor `cueID` contains implicit NA, consider using
## `forcats::fct_explicit_na`
\end{verbatim}

\begin{verbatim}
## # A tibble: 0 x 3
## # Groups:   category, cueID [1]
## # ... with 3 variables: category <int>, cueID <fct>, n <int>
\end{verbatim}

Great, each Fribble is unique!

\hypertarget{load-data}{%
\section{Load data}\label{load-data}}

List the files present in the folder, and load them.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df <-}\StringTok{ }\KeywordTok{list.files}\NormalTok{(}\KeywordTok{paste}\NormalTok{(localGitDir, }\StringTok{"/exp1/data/"}\NormalTok{, }\DataTypeTok{sep =} \StringTok{""}\NormalTok{)); }
\end{Highlighting}
\end{Shaded}

We have 4 files.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(df))\{}
  \KeywordTok{gsub}\NormalTok{(}\StringTok{".csv$"}\NormalTok{, }\StringTok{""}\NormalTok{, df[i]) ->}\StringTok{ }\NormalTok{id}
  \KeywordTok{assign}\NormalTok{(id, }\KeywordTok{data.frame}\NormalTok{())}
  \KeywordTok{read.csv}\NormalTok{(}\KeywordTok{paste}\NormalTok{(localGitDir, }\StringTok{"/exp1/data/"}\NormalTok{, df[i], }\DataTypeTok{sep =} \StringTok{""}\NormalTok{),}
           \DataTypeTok{na.strings=}\KeywordTok{c}\NormalTok{(}\StringTok{""}\NormalTok{,}\StringTok{"NA"}\NormalTok{),}
           \DataTypeTok{colClasses=}\KeywordTok{c}\NormalTok{(}\StringTok{"presentedLabel"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"presentedImage"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"learningType"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"Trial.Type"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"Test.Part"}\NormalTok{=}\StringTok{"factor"}\NormalTok{,}
                        \StringTok{"Key.Press"}\NormalTok{=}\StringTok{"factor"}
\NormalTok{                        ))->}\StringTok{ }\NormalTok{temp}
  \KeywordTok{assign}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(id), temp)}
\NormalTok{\};}

\KeywordTok{rm}\NormalTok{(temp, df, i, id);}
\end{Highlighting}
\end{Shaded}

The dataset name is decided autonomously by Gorilla. Importantly,
Gorilla produces a different file per condition, and codes the
conditions by the last 4 letters.

\begin{itemize}
\item
  2yjh is the FL learning
\item
  q8hp is the LF learning
\end{itemize}

I'm going to rename them for clarity.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dataFL<-}\StringTok{`}\DataTypeTok{data_exp_15519-v13_task-2yjh}\StringTok{`}
\NormalTok{dataFL2<-}\StringTok{`}\DataTypeTok{data_exp_15519-v14_task-2yjh}\StringTok{`}

\KeywordTok{rm}\NormalTok{(}\StringTok{`}\DataTypeTok{data_exp_15519-v13_task-2yjh}\StringTok{`}\NormalTok{)}
\KeywordTok{rm}\NormalTok{(}\StringTok{`}\DataTypeTok{data_exp_15519-v14_task-2yjh}\StringTok{`}\NormalTok{)}

\NormalTok{dataLF <-}\StringTok{ `}\DataTypeTok{data_exp_15519-v13_task-q8hp}\StringTok{`}
\NormalTok{dataLF2 <-}\StringTok{ `}\DataTypeTok{data_exp_15519-v14_task-q8hp}\StringTok{`}

\KeywordTok{rm}\NormalTok{(}\StringTok{`}\DataTypeTok{data_exp_15519-v13_task-q8hp}\StringTok{`}\NormalTok{)}
\KeywordTok{rm}\NormalTok{(}\StringTok{`}\DataTypeTok{data_exp_15519-v14_task-q8hp}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rbind}\NormalTok{(dataFL, dataFL2)->}\StringTok{ }\NormalTok{dataFL}
\KeywordTok{rbind}\NormalTok{(dataLF, dataLF2)->}\StringTok{ }\NormalTok{dataLF}

\KeywordTok{rm}\NormalTok{(dataFL2, dataLF2)}
\end{Highlighting}
\end{Shaded}

Gorilla's output is extremely messy. Each row is a screen event.
However, we want only the events related to 1. the presentations of the
fribbles and the labels 2. participants' response and 3. what type of
tasks.

I have coded these info in some columns and rows that I'm going to
select:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{raw_dataFL<-}\StringTok{ }\NormalTok{dataFL[}\KeywordTok{c}\NormalTok{(}\StringTok{'Participant.Private.ID'}\NormalTok{, }\StringTok{'learningType'}\NormalTok{, }\StringTok{'Test.Part'}\NormalTok{ , }
         \StringTok{'presentedImage'}\NormalTok{, }\StringTok{'presentedLabel'}\NormalTok{, }\StringTok{'Reaction.Time'}\NormalTok{, }\StringTok{"Key.Press"}\NormalTok{,}
          \StringTok{'Trial.Type'}\NormalTok{, }\StringTok{'Trial.Index'}\NormalTok{, }\StringTok{'Correct'}\NormalTok{)]}

\NormalTok{raw_dataLF<-}\StringTok{ }\NormalTok{dataLF[}\KeywordTok{c}\NormalTok{(}\StringTok{'Participant.Private.ID'}\NormalTok{, }\StringTok{'learningType'}\NormalTok{, }\StringTok{'Test.Part'}\NormalTok{ , }
         \StringTok{'presentedImage'}\NormalTok{, }\StringTok{'presentedLabel'}\NormalTok{, }\StringTok{'Reaction.Time'}\NormalTok{, }\StringTok{"Key.Press"}\NormalTok{,}
          \StringTok{'Trial.Type'}\NormalTok{, }\StringTok{'Trial.Index'}\NormalTok{, }\StringTok{'Correct'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

Select rows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rowsIwantTokeep <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"learningBlock1"}\NormalTok{, }\StringTok{"learningBlock2"}\NormalTok{, }\StringTok{"learningBlock3"}\NormalTok{,}
                        \StringTok{"learningBlock4"}\NormalTok{, }\StringTok{"generalizationPL"}\NormalTok{, }\StringTok{"generalizationLP"}\NormalTok{,}
                        \StringTok{"randomDot"}\NormalTok{, }\StringTok{"contingencyJudgement"}\NormalTok{)}

\NormalTok{raw_dataFL <-}\StringTok{ }\NormalTok{raw_dataFL }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(Test.Part }\OperatorTok{%in%}\StringTok{ }\NormalTok{rowsIwantTokeep ) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{rename}\NormalTok{(}\DataTypeTok{subjID =}\NormalTok{ Participant.Private.ID, }
         \DataTypeTok{learning =}\NormalTok{ learningType,}
         \DataTypeTok{task =}\NormalTok{ Test.Part, }
         \DataTypeTok{fribbleID =}\NormalTok{ presentedImage,}
         \DataTypeTok{label =}\NormalTok{ presentedLabel, }
         \DataTypeTok{rt =}\NormalTok{ Reaction.Time, }
         \DataTypeTok{resp =}\NormalTok{ Key.Press, }
         \DataTypeTok{trialType =}\NormalTok{ Trial.Type,}
         \DataTypeTok{trialIndex =}\NormalTok{ Trial.Index,}
         \DataTypeTok{acc =}\NormalTok{ Correct)}

\NormalTok{raw_dataLF <-}\StringTok{ }\NormalTok{raw_dataLF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(Test.Part }\OperatorTok{%in%}\StringTok{ }\NormalTok{rowsIwantTokeep ) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{rename}\NormalTok{(}\DataTypeTok{subjID =}\NormalTok{ Participant.Private.ID, }
         \DataTypeTok{learning =}\NormalTok{ learningType,}
         \DataTypeTok{task =}\NormalTok{ Test.Part, }
         \DataTypeTok{fribbleID =}\NormalTok{ presentedImage,}
         \DataTypeTok{label =}\NormalTok{ presentedLabel, }
         \DataTypeTok{rt =}\NormalTok{ Reaction.Time, }
         \DataTypeTok{resp =}\NormalTok{ Key.Press, }
         \DataTypeTok{trialType =}\NormalTok{ Trial.Type,}
         \DataTypeTok{trialIndex =}\NormalTok{ Trial.Index,}
         \DataTypeTok{acc =}\NormalTok{ Correct)}

\KeywordTok{rm}\NormalTok{(rowsIwantTokeep, dataFL, dataLF);}
\end{Highlighting}
\end{Shaded}

I'm going to merge both datasets, FL and LF, because we have anyway a
column ``learning'' that can tell us which one is which.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rbind}\NormalTok{(raw_dataFL, raw_dataLF)->}\StringTok{ }\NormalTok{raw_data; }
\KeywordTok{rm}\NormalTok{(raw_dataFL, raw_dataLF);}
\end{Highlighting}
\end{Shaded}

\hypertarget{check-learning}{%
\section{Check learning}\label{check-learning}}

Let's filter and check learning trials:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learningBlocks <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"learningBlock1"}\NormalTok{, }\StringTok{"learningBlock2"}\NormalTok{, }\StringTok{"learningBlock3"}\NormalTok{, }\StringTok{"learningBlock4"}\NormalTok{);}

\NormalTok{learning <-}\StringTok{ }\NormalTok{raw_data }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(task }\OperatorTok{%in%}\StringTok{ }\NormalTok{learningBlocks) }

\NormalTok{learning <-}\StringTok{ }\KeywordTok{droplevels}\NormalTok{(learning);}
\KeywordTok{rm}\NormalTok{(learningBlocks)}
\end{Highlighting}
\end{Shaded}

How many trials per participant?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learning }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, learning) }\OperatorTok{%>%}\StringTok{    }
\StringTok{  }\KeywordTok{count}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 80 x 3
## # Groups:   subjID, learning [80]
##     subjID learning     n
##      <int> <fct>    <int>
##  1 1414932 LF         120
##  2 1414933 LF         120
##  3 1414937 FL         120
##  4 1414945 FL         120
##  5 1414957 FL         120
##  6 1415040 FL         120
##  7 1420163 FL         120
##  8 1420165 FL         120
##  9 1420169 LF         120
## 10 1420171 LF         120
## # ... with 70 more rows
\end{verbatim}

Great, 120 trials per participant.

Let's check whether the blocks' length varied across participants:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learning }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, task) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 320 x 3
## # Groups:   subjID, task [320]
##     subjID task               n
##      <int> <fct>          <int>
##  1 1414932 learningBlock1    21
##  2 1414932 learningBlock2    28
##  3 1414932 learningBlock3    47
##  4 1414932 learningBlock4    24
##  5 1414933 learningBlock1    26
##  6 1414933 learningBlock2    22
##  7 1414933 learningBlock3    44
##  8 1414933 learningBlock4    28
##  9 1414937 learningBlock1    27
## 10 1414937 learningBlock2    47
## # ... with 310 more rows
\end{verbatim}

Great! Each participant had a different amount of trials distributed
across blocks. That's important because our random dot task was
presented at the end of each block, and we wanted its presentation to be
unpredictable. Anyway, the sum of all the learning trials was always
120.

Did we assign our learning randomly every couple of people?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(learning}\OperatorTok{$}\NormalTok{subjID, learning}\OperatorTok{$}\NormalTok{learning)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          
##            FL  LF
##   1414932   0 120
##   1414933   0 120
##   1414937 120   0
##   1414945 120   0
##   1414957 120   0
##   1415040 120   0
##   1420163 120   0
##   1420165 120   0
##   1420169   0 120
##   1420171   0 120
##   1420177 120   0
##   1420180 120   0
##   1420185   0 120
##   1420199 120   0
##   1420204   0 120
##   1420552   0 120
##   1420573   0 120
##   1420577   0 120
##   1420580 120   0
##   1420622 120   0
##   1422463 120   0
##   1422465 120   0
##   1422466 120   0
##   1422467   0 120
##   1422470   0 120
##   1422472 120   0
##   1422473   0 120
##   1422475   0 120
##   1422476   0 120
##   1422477 120   0
##   1422675 120   0
##   1422676   0 120
##   1422677 120   0
##   1422678   0 120
##   1422679 120   0
##   1422680   0 120
##   1422681   0 120
##   1422689 120   0
##   1422715   0 120
##   1422716 120   0
##   1431942   0 120
##   1431944 120   0
##   1431946 120   0
##   1431948   0 120
##   1431949 120   0
##   1431952   0 120
##   1431953 120   0
##   1431954   0 120
##   1431956   0 120
##   1431957 120   0
##   1431958 120   0
##   1431959   0 120
##   1431960   0 120
##   1431961 120   0
##   1431963   0 120
##   1431965 120   0
##   1431966   0 120
##   1431968   0 120
##   1431969 120   0
##   1431970   0 120
##   1431972 120   0
##   1431974 120   0
##   1431978 120   0
##   1431979 120   0
##   1431981   0 120
##   1431984 120   0
##   1431989   0 120
##   1431992 120   0
##   1431997 120   0
##   1431998   0 120
##   1431999   0 120
##   1432003   0 120
##   1432007   0 120
##   1432009 120   0
##   1432011 120   0
##   1432030   0 120
##   1432052 120   0
##   1432075 120   0
##   1432301   0 120
##   1432323   0 120
\end{verbatim}

Kind of. Apparently, if a participant access Gorilla, but it's not
allowed to start the experiment (e.g., the browser is not suitable), or
leaves the session, this counts anyway for the randomisation.

The rows related to the presentation of fribbles and labels, inherit
Gorilla's http address of where they are stored. Nothing I can do to
change this in Gorilla, but we can clean the rows by those info like
this:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{"/task/70033/56/asset/|/task/70033/57/asset/"}\NormalTok{, }\StringTok{""}\NormalTok{, learning}\OperatorTok{$}\NormalTok{fribbleID))->}\StringTok{ }\NormalTok{learning}\OperatorTok{$}\NormalTok{fribbleID}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".jpg$"}\NormalTok{, }\StringTok{""}\NormalTok{, learning}\OperatorTok{$}\NormalTok{fribbleID))->}\StringTok{ }\NormalTok{learning}\OperatorTok{$}\NormalTok{fribbleID}

\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{"/task/70033/56/asset/|/task/70033/57/asset/"}\NormalTok{, }\StringTok{""}\NormalTok{, learning}\OperatorTok{$}\NormalTok{label))->}\StringTok{ }\NormalTok{learning}\OperatorTok{$}\NormalTok{label}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".mp3$"}\NormalTok{, }\StringTok{""}\NormalTok{, learning}\OperatorTok{$}\NormalTok{label))->}\StringTok{ }\NormalTok{learning}\OperatorTok{$}\NormalTok{label}
\NormalTok{learning}\OperatorTok{$}\NormalTok{resp <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(}\StringTok{'NA'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

This is how the learning dataframe looks like now:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(learning);}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    subjID learning           task fribbleID label rt resp
## 1 1414937       FL learningBlock1     20375 FLbim NA   NA
## 2 1414937       FL learningBlock1     31075 FLtob NA   NA
## 3 1414937       FL learningBlock1     32775 FLtob NA   NA
## 4 1414937       FL learningBlock1     32875 FLtob NA   NA
## 5 1414937       FL learningBlock1     22025 FLbim NA   NA
## 6 1414937       FL learningBlock1     10425 FLdep NA   NA
##                 trialType trialIndex acc
## 1 audio-keyboard-response         22  NA
## 2 audio-keyboard-response         25  NA
## 3 audio-keyboard-response         28  NA
## 4 audio-keyboard-response         31  NA
## 5 audio-keyboard-response         34  NA
## 6 audio-keyboard-response         37  NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(learning);}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      subjID        learning              task        fribbleID      label     
##  Min.   :1414932   FL:4920   learningBlock1:2283   10975  :  86   FLbim:1640  
##  1st Qu.:1422003   LF:4680   learningBlock2:2549   22575  :  84   FLdep:1640  
##  Median :1427329             learningBlock3:2336   31975  :  84   FLtob:1640  
##  Mean   :1426320             learningBlock4:2432   32675  :  84   LFbim:1560  
##  3rd Qu.:1431971                                   21875  :  82   LFdep:1560  
##  Max.   :1432323                                   30375  :  82   LFtob:1560  
##                                                    (Other):9098               
##        rt         resp                        trialType      trialIndex 
##  Min.   : 12.36   NA:9600   audio-keyboard-response:4920   Min.   : 22  
##  1st Qu.: 52.50             image-keyboard-response:4680   1st Qu.:115  
##  Median : 88.00                                            Median :211  
##  Mean   :126.25                                            Mean   :211  
##  3rd Qu.:214.71                                            3rd Qu.:307  
##  Max.   :249.00                                            Max.   :400  
##  NA's   :9593                                                           
##       acc      
##  Min.   : NA   
##  1st Qu.: NA   
##  Median : NA   
##  Mean   :NaN   
##  3rd Qu.: NA   
##  Max.   : NA   
##  NA's   :9600
\end{verbatim}

Our fribbles were presented two times during learning. Let's check
fribbles presented \textgreater{} 2 times:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learning }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, fribbleID) }\OperatorTok{%>%}\StringTok{    }
\StringTok{  }\KeywordTok{count}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{>}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Factor `fribbleID` contains implicit NA, consider using
## `forcats::fct_explicit_na`
\end{verbatim}

\begin{verbatim}
## # A tibble: 0 x 3
## # Groups:   subjID, fribbleID [1]
## # ... with 3 variables: subjID <int>, fribbleID <fct>, n <int>
\end{verbatim}

None, perfect. Let's check whether there are fribbles presented only
once:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learning }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, fribbleID) }\OperatorTok{%>%}\StringTok{    }
\StringTok{  }\KeywordTok{count}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{<}\StringTok{ }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Factor `fribbleID` contains implicit NA, consider using
## `forcats::fct_explicit_na`
\end{verbatim}

\begin{verbatim}
## # A tibble: 0 x 3
## # Groups:   subjID, fribbleID [1]
## # ... with 3 variables: subjID <int>, fribbleID <fct>, n <int>
\end{verbatim}

Perfect.

Check the association between the fribbles and the labels. Fribbles ID
are coded in this way: e.g., 10175-\textgreater{} {[}1{]} is the
category {[}01{]} is the number of the fribble {[}75{]} is the
frequency.

In the column fribbleID we have the fribble presented, in the column
label we have the sound played.

Association between fribbles and labels are fixed:

\begin{itemize}
\item
  category 1, regardless of the frequency, has the label: dep
\item
  category 2, regardless of the frequency, has the label: bim
\item
  category 3, regardless of the frequency, has the label: tob
\end{itemize}

I'm going to add a column for category, fribble number, and frequency,
in order to check whether everything is okay:

We should have only 3 categories, presented twice per participant. Each
category is made of 20 exemplars.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learning}\OperatorTok{$}\NormalTok{category <-}\StringTok{ }\DecValTok{0}
\NormalTok{learning[}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(learning}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)}\OperatorTok{==}\DecValTok{1}\NormalTok{,]}\OperatorTok{$}\NormalTok{category <-}\StringTok{ }\DecValTok{1}
\NormalTok{learning[}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(learning}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)}\OperatorTok{==}\DecValTok{2}\NormalTok{,]}\OperatorTok{$}\NormalTok{category <-}\StringTok{ }\DecValTok{2}
\NormalTok{learning[}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(learning}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)}\OperatorTok{==}\DecValTok{3}\NormalTok{,]}\OperatorTok{$}\NormalTok{category <-}\StringTok{ }\DecValTok{3}

\NormalTok{(}\KeywordTok{nrow}\NormalTok{(learning[learning}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{1}\NormalTok{,]) }\OperatorTok{/}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(learning}\OperatorTok{$}\NormalTok{subjID))) }\OperatorTok{/}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\KeywordTok{nrow}\NormalTok{(learning[learning}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{2}\NormalTok{,]) }\OperatorTok{/}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(learning}\OperatorTok{$}\NormalTok{subjID))) }\OperatorTok{/}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\KeywordTok{nrow}\NormalTok{(learning[learning}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{3}\NormalTok{,]) }\OperatorTok{/}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(learning}\OperatorTok{$}\NormalTok{subjID))) }\OperatorTok{/}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20
\end{verbatim}

We have 15 high frequency and 5 low frequency exemplars x category:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{learning}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\DecValTok{25}
\NormalTok{learning[}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(learning}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)}\OperatorTok{==}\DecValTok{75}\NormalTok{,]}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\DecValTok{75}

\NormalTok{(}\KeywordTok{nrow}\NormalTok{(learning[learning}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\DecValTok{25}\NormalTok{,]) }\OperatorTok{/}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(learning}\OperatorTok{$}\NormalTok{subjID))) }\OperatorTok{/}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\KeywordTok{nrow}\NormalTok{(learning[learning}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\DecValTok{75}\NormalTok{,]) }\OperatorTok{/}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(learning}\OperatorTok{$}\NormalTok{subjID))) }\OperatorTok{/}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 45
\end{verbatim}

Now let's check the fribble-label association:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(learning}\OperatorTok{$}\NormalTok{category, learning}\OperatorTok{$}\NormalTok{label, learning}\OperatorTok{$}\NormalTok{frequency)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## , ,  = 25
## 
##    
##     FLbim FLdep FLtob LFbim LFdep LFtob
##   1     0   410     0     0   390     0
##   2   410     0     0   390     0     0
##   3     0     0   410     0     0   390
## 
## , ,  = 75
## 
##    
##     FLbim FLdep FLtob LFbim LFdep LFtob
##   1     0  1230     0     0  1170     0
##   2  1230     0     0  1170     0     0
##   3     0     0  1230     0     0  1170
\end{verbatim}

Okay, each label was associated to its correct fribble (coded here as
category).

\hypertarget{check-testing}{%
\section{Check Testing}\label{check-testing}}

I'm going to select the tests and clean the rows from Gorilla's http
address:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tests <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"generalizationPL"}\NormalTok{, }\StringTok{"generalizationLP"}\NormalTok{, }\StringTok{"contingencyJudgement"}\NormalTok{, }\StringTok{"randomDot"}\NormalTok{);}

\NormalTok{testing <-}\StringTok{ }\NormalTok{raw_data }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(task }\OperatorTok{%in%}\StringTok{ }\NormalTok{tests)  }


\NormalTok{testing <-}\StringTok{ }\KeywordTok{droplevels}\NormalTok{(testing);}
\KeywordTok{rm}\NormalTok{(tests);}

\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{"/task/70033/56/asset/|/task/70033/57/asset/"}\NormalTok{, }\StringTok{""}\NormalTok{, testing}\OperatorTok{$}\NormalTok{fribbleID))->}\StringTok{ }\NormalTok{testing}\OperatorTok{$}\NormalTok{fribbleID}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".jpg$"}\NormalTok{, }\StringTok{""}\NormalTok{, testing}\OperatorTok{$}\NormalTok{fribbleID))->}\StringTok{ }\NormalTok{testing}\OperatorTok{$}\NormalTok{fribbleID}

\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{"/task/70033/56/asset/|/task/70033/57/asset/"}\NormalTok{, }\StringTok{""}\NormalTok{, testing}\OperatorTok{$}\NormalTok{label))->}\StringTok{ }\NormalTok{testing}\OperatorTok{$}\NormalTok{label}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".mp3$"}\NormalTok{, }\StringTok{""}\NormalTok{, testing}\OperatorTok{$}\NormalTok{label))->}\StringTok{ }\NormalTok{testing}\OperatorTok{$}\NormalTok{label}
\end{Highlighting}
\end{Shaded}

\hypertarget{check-test-1-generalization-from-picture-to-labels}{%
\subsection{Check test 1: Generalization from picture to
labels}\label{check-test-1-generalization-from-picture-to-labels}}

We filter the rows for this task, and clean both the resp and fribble
columns.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationPL <-}\StringTok{ }\NormalTok{testing }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(task }\OperatorTok{==}\StringTok{ 'generalizationPL'}\NormalTok{) }
\NormalTok{generalizationPL <-}\StringTok{ }\KeywordTok{droplevels}\NormalTok{(generalizationPL);}

\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{"/task/70033/56/asset/|/task/70033/57/asset/"}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationPL}\OperatorTok{$}\NormalTok{resp))->}\StringTok{ }\NormalTok{generalizationPL}\OperatorTok{$}\NormalTok{resp}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".mp3$"}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationPL}\OperatorTok{$}\NormalTok{resp))->}\StringTok{ }\NormalTok{generalizationPL}\OperatorTok{$}\NormalTok{resp}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".jpg"}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationPL}\OperatorTok{$}\NormalTok{resp))->}\StringTok{ }\NormalTok{generalizationPL}\OperatorTok{$}\NormalTok{resp}

\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{'[[:punct:]]|"'}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationPL}\OperatorTok{$}\NormalTok{label))->}\StringTok{ }\NormalTok{generalizationPL}\OperatorTok{$}\NormalTok{label }
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{'mp3'}\NormalTok{, }\StringTok{"_"}\NormalTok{, generalizationPL}\OperatorTok{$}\NormalTok{label))->}\StringTok{ }\NormalTok{generalizationPL}\OperatorTok{$}\NormalTok{label}
\end{Highlighting}
\end{Shaded}

Check how many trials participants:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationPL }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 80 x 2
## # Groups:   subjID [80]
##     subjID     n
##      <int> <int>
##  1 1414932    24
##  2 1414933    24
##  3 1414937    24
##  4 1414945    24
##  5 1414957    24
##  6 1415040    24
##  7 1420163    24
##  8 1420165    24
##  9 1420169    24
## 10 1420171    24
## # ... with 70 more rows
\end{verbatim}

Great, 24 trials per participant.

Check whether participants saw a unique fribble:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationPL }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, fribbleID) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{>}\StringTok{ }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Factor `fribbleID` contains implicit NA, consider using
## `forcats::fct_explicit_na`
\end{verbatim}

\begin{verbatim}
## # A tibble: 0 x 3
## # Groups:   subjID, fribbleID [1]
## # ... with 3 variables: subjID <int>, fribbleID <fct>, n <int>
\end{verbatim}

Great!

Integrate stimuli info. In the file ``fribbleSet'' I have listed all the
fribbles ID and their category, along with their cueIDs and body shape.
I'm going to add those columns by merging the test file with the
fribbleSet by fribbleID. The rest of the file is left untouched.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{merge}\NormalTok{(generalizationPL, fribbleSet, }\DataTypeTok{by =} \StringTok{'fribbleID'}\NormalTok{)->}\StringTok{ }\NormalTok{generalizationPL;}
\NormalTok{generalizationPL}\OperatorTok{$}\NormalTok{label.y <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}

\NormalTok{generalizationPL <-}\StringTok{ }\KeywordTok{rename}\NormalTok{(generalizationPL, }\DataTypeTok{label =}\NormalTok{ label.x);}
\end{Highlighting}
\end{Shaded}

Let's check the responses they made, just to see if they make sense.

For example, we want the resp column to be one of the labels.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationPL }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, resp) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Factor `resp` contains implicit NA, consider using
## `forcats::fct_explicit_na`

## Warning: Factor `resp` contains implicit NA, consider using
## `forcats::fct_explicit_na`

## Warning: Factor `resp` contains implicit NA, consider using
## `forcats::fct_explicit_na`
\end{verbatim}

\begin{verbatim}
## # A tibble: 291 x 3
## # Groups:   subjID, resp [291]
##     subjID resp      n
##      <int> <fct> <int>
##  1 1414932 bim       6
##  2 1414932 dep       5
##  3 1414932 tob       9
##  4 1414932 <NA>      4
##  5 1414933 bim       8
##  6 1414933 dep       8
##  7 1414933 tob       8
##  8 1414937 bim       8
##  9 1414937 dep       7
## 10 1414937 tob       8
## # ... with 281 more rows
\end{verbatim}

Great, some participant missed some trials (coded as NA), but that's
okay.

So far, so good.

We have 24 trials per participant, but within those trials we have 8
trials per category, 4 low frequency and 4 high frequency trials. Let's
check:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(}\KeywordTok{table}\NormalTok{(generalizationPL}\OperatorTok{$}\NormalTok{subjID, generalizationPL}\OperatorTok{$}\NormalTok{category, generalizationPL}\OperatorTok{$}\NormalTok{frequency))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## , ,  = 25
## 
##          
##           1 2 3
##   1414932 4 4 4
##   1414933 4 4 4
##   1414937 4 4 4
##   1414945 4 4 4
##   1414957 4 4 4
##   1415040 4 4 4
## 
## , ,  = 75
## 
##          
##           1 2 3
##   1414932 4 4 4
##   1414933 4 4 4
##   1414937 4 4 4
##   1414945 4 4 4
##   1414957 4 4 4
##   1415040 4 4 4
\end{verbatim}

Let's check the second task.

\hypertarget{check-test-2-generalization-from-label-to-pictures}{%
\subsection{Check test 2: Generalization from label to
pictures}\label{check-test-2-generalization-from-label-to-pictures}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationLP <-}\StringTok{ }\NormalTok{testing }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(task }\OperatorTok{==}\StringTok{ 'generalizationLP'}\NormalTok{) }
\NormalTok{generalizationLP <-}\StringTok{ }\KeywordTok{droplevels}\NormalTok{(generalizationLP)}
\end{Highlighting}
\end{Shaded}

How many trials per participant?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationLP }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 80 x 2
## # Groups:   subjID [80]
##     subjID     n
##      <int> <int>
##  1 1414932    24
##  2 1414933    24
##  3 1414937    24
##  4 1414945    24
##  5 1414957    24
##  6 1415040    24
##  7 1420163    24
##  8 1420165    24
##  9 1420169    24
## 10 1420171    24
## # ... with 70 more rows
\end{verbatim}

24 trials, great.

Let's check whether participants saw a unique fribble by checking for
duplicates: First let's clean the rows from Gorilla gibberish.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{'[[:punct:]]|"'}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationLP}\OperatorTok{$}\NormalTok{fribbleID))->}\StringTok{ }\NormalTok{generalizationLP}\OperatorTok{$}\NormalTok{fribbleID }
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{'jpg'}\NormalTok{, }\StringTok{"_"}\NormalTok{, generalizationLP}\OperatorTok{$}\NormalTok{fribbleID))->}\StringTok{ }\NormalTok{generalizationLP}\OperatorTok{$}\NormalTok{fribbleID}

\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{"/task/70033/56/asset/|/task/70033/57/asset/"}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationLP}\OperatorTok{$}\NormalTok{resp))->}\StringTok{ }\NormalTok{generalizationLP}\OperatorTok{$}\NormalTok{resp}
\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{gsub}\NormalTok{(}\StringTok{".jpg"}\NormalTok{, }\StringTok{""}\NormalTok{, generalizationLP}\OperatorTok{$}\NormalTok{resp))->}\StringTok{ }\NormalTok{generalizationLP}\OperatorTok{$}\NormalTok{resp}
\end{Highlighting}
\end{Shaded}

Then check for duplicates:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{1}\NormalTok{, }\DecValTok{5}\NormalTok{)->}\StringTok{ }\NormalTok{temp}
\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{7}\NormalTok{, }\DecValTok{11}\NormalTok{)->}\StringTok{ }\NormalTok{temp2}
\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{13}\NormalTok{, }\DecValTok{17}\NormalTok{)->}\StringTok{ }\NormalTok{temp3}

\NormalTok{fribblePresented <-}\StringTok{ }\KeywordTok{c}\NormalTok{(temp,temp2,temp3)}
\KeywordTok{unique}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{subjID)->}\StringTok{ }\NormalTok{subj}

\NormalTok{duplicatedFribbles <-}\StringTok{ }\OtherTok{NA}\NormalTok{;}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(subj))\{}
  \KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{subjID}\OperatorTok{==}\NormalTok{subj[i],]}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{1}\NormalTok{, }\DecValTok{5}\NormalTok{)->}\StringTok{ }\NormalTok{temp}
  \KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{subjID}\OperatorTok{==}\NormalTok{subj[i],]}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{7}\NormalTok{, }\DecValTok{11}\NormalTok{)->}\StringTok{ }\NormalTok{temp2}
  \KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{subjID}\OperatorTok{==}\NormalTok{subj[i],]}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{13}\NormalTok{, }\DecValTok{17}\NormalTok{)->}\StringTok{ }\NormalTok{temp3}
\NormalTok{  fribblePresented <-}\StringTok{ }\KeywordTok{c}\NormalTok{(temp,temp2,temp3)}
\NormalTok{  dup <-}\StringTok{ }\NormalTok{fribblePresented[}\KeywordTok{duplicated}\NormalTok{(fribblePresented)] }\CommentTok{#extract duplicated elements}
  \KeywordTok{print}\NormalTok{(subj[i])}
  
  \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{length}\NormalTok{(dup)}\OperatorTok{>}\DecValTok{0}\NormalTok{)\{}
    \KeywordTok{print}\NormalTok{(dup)}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
    \KeywordTok{print}\NormalTok{(}\KeywordTok{length}\NormalTok{(dup))}
\NormalTok{  \}}
  
\NormalTok{\};}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1414937
## [1] 0
## [1] 1414945
## [1] 0
## [1] 1414957
## [1] 0
## [1] 1415040
## [1] 0
## [1] 1431949
## [1] 0
## [1] 1431944
## [1] 0
## [1] 1431953
## [1] 0
## [1] 1431958
## [1] 0
## [1] 1431965
## [1] 0
## [1] 1431946
## [1] 0
## [1] 1431957
## [1] 0
## [1] 1431961
## [1] 0
## [1] 1431969
## [1] 0
## [1] 1431978
## [1] 0
## [1] 1431979
## [1] 0
## [1] 1422477
## [1] 0
## [1] 1422675
## [1] 0
## [1] 1422677
## [1] 0
## [1] 1422679
## [1] 0
## [1] 1422689
## [1] 0
## [1] 1422716
## [1] 0
## [1] 1431972
## [1] 0
## [1] 1431974
## [1] 0
## [1] 1431984
## [1] 0
## [1] 1431992
## [1] 0
## [1] 1431997
## [1] 0
## [1] 1432009
## [1] 0
## [1] 1432011
## [1] 0
## [1] 1432052
## [1] 0
## [1] 1432075
## [1] 0
## [1] 1420163
## [1] 0
## [1] 1420165
## [1] 0
## [1] 1420177
## [1] 0
## [1] 1420180
## [1] 0
## [1] 1420199
## [1] 0
## [1] 1420580
## [1] 0
## [1] 1420622
## [1] 0
## [1] 1422463
## [1] 0
## [1] 1422465
## [1] 0
## [1] 1422466
## [1] 0
## [1] 1422472
## [1] 0
## [1] 1414933
## [1] 0
## [1] 1414932
## [1] 0
## [1] 1420169
## [1] 0
## [1] 1420171
## [1] 0
## [1] 1420577
## [1] 0
## [1] 1422467
## [1] 0
## [1] 1422475
## [1] 0
## [1] 1422678
## [1] 0
## [1] 1422680
## [1] 0
## [1] 1422681
## [1] 0
## [1] 1431942
## [1] 0
## [1] 1431948
## [1] 0
## [1] 1431966
## [1] 0
## [1] 1431968
## [1] 0
## [1] 1431952
## [1] 0
## [1] 1431954
## [1] 0
## [1] 1431956
## [1] 0
## [1] 1431959
## [1] 0
## [1] 1431960
## [1] 0
## [1] 1431963
## [1] 0
## [1] 1431970
## [1] 0
## [1] 1431981
## [1] 0
## [1] 1431989
## [1] 0
## [1] 1431998
## [1] 0
## [1] 1431999
## [1] 0
## [1] 1432003
## [1] 0
## [1] 1432007
## [1] 0
## [1] 1432030
## [1] 0
## [1] 1420185
## [1] 0
## [1] 1420204
## [1] 0
## [1] 1420552
## [1] 0
## [1] 1420573
## [1] 0
## [1] 1422470
## [1] 0
## [1] 1422473
## [1] 0
## [1] 1422476
## [1] 0
## [1] 1422676
## [1] 0
## [1] 1422715
## [1] 0
## [1] 1432301
## [1] 0
## [1] 1432323
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(subj, temp, temp2, temp3, i, fribblePresented, duplicatedFribbles, dup)}
\end{Highlighting}
\end{Shaded}

Great! participants saw always different fribble.

Check whether fribbles presented were either high or low frequency.

In this task we have three pictures and one label pronounced. This means
that the fribbleID column contains 3 images. I'm going to cycle over the
dataset, and break the fribbleID column in three, then I'm going to
print the fribble that within the same trial has a different frequency.
I'm going to print the fribbles that are presented wrongly, e.g., ``low
high low'' etc. If all fribbles are presented correctly: , e.g., ``low
low low'' and ``high high high'', then the output is empty.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{unique}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{subjID)->}\StringTok{ }\NormalTok{subj;}

\NormalTok{trials <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}
\NormalTok{task <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(subj))\{}
  \KeywordTok{as.integer}\NormalTok{(}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{subjID}\OperatorTok{==}\NormalTok{subj[i],]}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{))->}\StringTok{ }\NormalTok{temp }\CommentTok{#first fribble}
  \KeywordTok{as.integer}\NormalTok{(}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{subjID}\OperatorTok{==}\NormalTok{subj[i],]}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{10}\NormalTok{, }\DecValTok{11}\NormalTok{))->}\StringTok{ }\NormalTok{temp2 }\CommentTok{#second fribble}
  \KeywordTok{as.integer}\NormalTok{(}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{subjID}\OperatorTok{==}\NormalTok{subj[i],]}\OperatorTok{$}\NormalTok{fribbleID), }\DecValTok{16}\NormalTok{, }\DecValTok{17}\NormalTok{))->}\StringTok{ }\NormalTok{temp3 }\CommentTok{#third fribble}
\NormalTok{trials <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(temp, temp2, temp3, }\KeywordTok{as.integer}\NormalTok{(subj[i])) }\CommentTok{# store it in columns along with subj info}
\NormalTok{task <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(task, trials) }\CommentTok{#store all subjs}
\NormalTok{\};}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(task))\{ }\CommentTok{#check by rows whether there is a unique number, print the row if wrong}
  \ControlFlowTok{if}\NormalTok{ ((task[i,}\DecValTok{1}\NormalTok{] }\OperatorTok{==}\StringTok{ }\NormalTok{task[i,}\DecValTok{2}\NormalTok{] }\OperatorTok{&}\StringTok{ }\NormalTok{task[i,}\DecValTok{3}\NormalTok{])}\OperatorTok{==}\StringTok{ }\OtherTok{FALSE}\NormalTok{) \{}
    \KeywordTok{print}\NormalTok{(}\StringTok{'wrong frequency fribble:'}\NormalTok{)}
    \KeywordTok{print}\NormalTok{(task[i,}\DecValTok{1}\NormalTok{], task[i,}\DecValTok{2}\NormalTok{], task[i,}\DecValTok{3}\NormalTok{])}
\NormalTok{  \} }
\NormalTok{\};}

\NormalTok{frequency <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(}\KeywordTok{substr}\NormalTok{(}\KeywordTok{as.character}\NormalTok{(task[,}\DecValTok{1}\NormalTok{]), }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)}\OperatorTok{==}\DecValTok{2}\NormalTok{, }\StringTok{'low'}\NormalTok{, }\StringTok{'high'}\NormalTok{)}
\KeywordTok{cbind}\NormalTok{(task, frequency)->task}
\KeywordTok{as.data.frame}\NormalTok{(task)->}\StringTok{ }\NormalTok{task}
\KeywordTok{rm}\NormalTok{(trials, i, subj, temp, temp2, temp3);}
\end{Highlighting}
\end{Shaded}

Great, fribbles presented were either low or high frequency. Check
whether participants saw 4 trials with low and 4 trials with high
frequency:

Let's see how these are distributed:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(}\KeywordTok{table}\NormalTok{(task}\OperatorTok{$}\NormalTok{V4, task}\OperatorTok{$}\NormalTok{frequency))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          
##           high low
##   1414932   12  12
##   1414933   12  12
##   1414937   12  12
##   1414945   12  12
##   1414957   12  12
##   1415040   12  12
\end{verbatim}

I'm going to merge the stimuli set now.

When we do it, this time we need to merge by resp and not by fribbleID,
because our fribble selected is coded in this column:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fribbleSet}\OperatorTok{$}\NormalTok{resp <-}\StringTok{ }\NormalTok{fribbleSet}\OperatorTok{$}\NormalTok{fribbleID }\CommentTok{# column's name needs to be the same in order to merge}
\KeywordTok{merge}\NormalTok{(generalizationLP, fribbleSet, }\DataTypeTok{by =} \StringTok{'resp'}\NormalTok{, }\DataTypeTok{all.x =}\NormalTok{ T)->}\StringTok{ }\NormalTok{generalizationLP;}
\NormalTok{fribbleSet}\OperatorTok{$}\NormalTok{resp <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}
\NormalTok{generalizationLP}\OperatorTok{$}\NormalTok{fribbleID.y <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}
\NormalTok{generalizationLP}\OperatorTok{$}\NormalTok{label.y <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}
\NormalTok{generalizationLP <-}\StringTok{ }\KeywordTok{rename}\NormalTok{(generalizationLP, }\DataTypeTok{label =}\NormalTok{ label.x);}
\NormalTok{generalizationLP <-}\StringTok{ }\KeywordTok{rename}\NormalTok{(generalizationLP, }\DataTypeTok{fribbleID =}\NormalTok{ fribbleID.x);}
\end{Highlighting}
\end{Shaded}

Let's check whether we have responses in all the three categories:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationLP }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, category) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 295 x 3
## # Groups:   subjID, category [295]
##     subjID category     n
##      <int>    <int> <int>
##  1 1414932        1     7
##  2 1414932        2    11
##  3 1414932        3     2
##  4 1414932       NA     4
##  5 1414933        1     8
##  6 1414933        2     5
##  7 1414933        3    10
##  8 1414933       NA     1
##  9 1414937        1     7
## 10 1414937        2     7
## # ... with 285 more rows
\end{verbatim}

Cool.

Check responses distribution over category:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{generalizationLP }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, label, frequency) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 583 x 4
## # Groups:   subjID, label, frequency [583]
##     subjID label frequency     n
##      <int> <fct>     <int> <int>
##  1 1414932 bim          25     3
##  2 1414932 bim          75     4
##  3 1414932 bim          NA     1
##  4 1414932 dep          25     3
##  5 1414932 dep          75     3
##  6 1414932 dep          NA     2
##  7 1414932 tob          25     3
##  8 1414932 tob          75     4
##  9 1414932 tob          NA     1
## 10 1414933 bim          25     4
## # ... with 573 more rows
\end{verbatim}

\hypertarget{check-test-3-contingency-judgement-task}{%
\subsection{Check test 3: Contingency Judgement
task}\label{check-test-3-contingency-judgement-task}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{contingencyJudgement <-}\StringTok{ }\NormalTok{testing }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(task }\OperatorTok{==}\StringTok{ 'contingencyJudgement'}\NormalTok{) }
\NormalTok{contingencyJudgement <-}\StringTok{ }\KeywordTok{droplevels}\NormalTok{(contingencyJudgement)}
\end{Highlighting}
\end{Shaded}

How many trials per participant?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{contingencyJudgement }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 80 x 2
## # Groups:   subjID [80]
##     subjID     n
##      <int> <int>
##  1 1414932    24
##  2 1414933    24
##  3 1414937    24
##  4 1414945    24
##  5 1414957    24
##  6 1415040    24
##  7 1420163    24
##  8 1420165    24
##  9 1420169    24
## 10 1420171    24
## # ... with 70 more rows
\end{verbatim}

Very good.

Did participants see a fribble more than once?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{droplevels}\NormalTok{(contingencyJudgement) }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, fribbleID) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{( n }\OperatorTok{>}\StringTok{ }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Factor `fribbleID` contains implicit NA, consider using
## `forcats::fct_explicit_na`
\end{verbatim}

\begin{verbatim}
## # A tibble: 0 x 3
## # Groups:   subjID, fribbleID [1]
## # ... with 3 variables: subjID <int>, fribbleID <fct>, n <int>
\end{verbatim}

No! that's great.

Are labels repeated equally?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(contingencyJudgement}\OperatorTok{$}\NormalTok{subjID, contingencyJudgement}\OperatorTok{$}\NormalTok{label)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          
##           bim dep tob
##   1414932   8   8   8
##   1414933   8   8   8
##   1414937   8   8   8
##   1414945   8   8   8
##   1414957   8   8   8
##   1415040   8   8   8
##   1420163   8   8   8
##   1420165   8   8   8
##   1420169   8   8   8
##   1420171   8   8   8
##   1420177   8   8   8
##   1420180   8   8   8
##   1420185   8   8   8
##   1420199   8   8   8
##   1420204   8   8   8
##   1420552   8   8   8
##   1420573   8   8   8
##   1420577   8   8   8
##   1420580   8   8   8
##   1420622   8   8   8
##   1422463   8   8   8
##   1422465   8   8   8
##   1422466   8   8   8
##   1422467   8   8   8
##   1422470   8   8   8
##   1422472   8   8   8
##   1422473   8   8   8
##   1422475   8   8   8
##   1422476   8   8   8
##   1422477   8   8   8
##   1422675   8   8   8
##   1422676   8   8   8
##   1422677   8   8   8
##   1422678   8   8   8
##   1422679   8   8   8
##   1422680   8   8   8
##   1422681   8   8   8
##   1422689   8   8   8
##   1422715   8   8   8
##   1422716   8   8   8
##   1431942   8   8   8
##   1431944   8   8   8
##   1431946   8   8   8
##   1431948   8   8   8
##   1431949   8   8   8
##   1431952   8   8   8
##   1431953   8   8   8
##   1431954   8   8   8
##   1431956   8   8   8
##   1431957   8   8   8
##   1431958   8   8   8
##   1431959   8   8   8
##   1431960   8   8   8
##   1431961   8   8   8
##   1431963   8   8   8
##   1431965   8   8   8
##   1431966   8   8   8
##   1431968   8   8   8
##   1431969   8   8   8
##   1431970   8   8   8
##   1431972   8   8   8
##   1431974   8   8   8
##   1431978   8   8   8
##   1431979   8   8   8
##   1431981   8   8   8
##   1431984   8   8   8
##   1431989   8   8   8
##   1431992   8   8   8
##   1431997   8   8   8
##   1431998   8   8   8
##   1431999   8   8   8
##   1432003   8   8   8
##   1432007   8   8   8
##   1432009   8   8   8
##   1432011   8   8   8
##   1432030   8   8   8
##   1432052   8   8   8
##   1432075   8   8   8
##   1432301   8   8   8
##   1432323   8   8   8
\end{verbatim}

good

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{merge}\NormalTok{(contingencyJudgement, fribbleSet, }\DataTypeTok{by =} \StringTok{'fribbleID'}\NormalTok{)->}\StringTok{ }\NormalTok{contingencyJudgement}
\NormalTok{contingencyJudgement}\OperatorTok{$}\NormalTok{label.y <-}\StringTok{ }\OtherTok{NULL}\NormalTok{;}
\NormalTok{contingencyJudgement <-}\StringTok{ }\KeywordTok{rename}\NormalTok{(contingencyJudgement, }\DataTypeTok{label =}\NormalTok{ label.x)}
\end{Highlighting}
\end{Shaded}

Check category presentation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{contingencyJudgement }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, category) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 240 x 3
## # Groups:   subjID, category [240]
##     subjID category     n
##      <int>    <int> <int>
##  1 1414932        1     8
##  2 1414932        2     8
##  3 1414932        3     8
##  4 1414933        1     8
##  5 1414933        2     8
##  6 1414933        3     8
##  7 1414937        1     8
##  8 1414937        2     8
##  9 1414937        3     8
## 10 1414945        1     8
## # ... with 230 more rows
\end{verbatim}

\hypertarget{check-test-4-random-dot-task}{%
\subsection{Check test 4: Random dot
task}\label{check-test-4-random-dot-task}}

Let's check our random dot task. This was inserted randomly during
trials 4 times. 5 trials each time, plus 4 practice trials.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{randomDot <-}\StringTok{ }\NormalTok{testing }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(task }\OperatorTok{==}\StringTok{ 'randomDot'}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

How many trials per participant?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{randomDot }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{count}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 80 x 2
## # Groups:   subjID [80]
##     subjID     n
##      <int> <int>
##  1 1414932    26
##  2 1414933    26
##  3 1414937    26
##  4 1414945    26
##  5 1414957    26
##  6 1415040    26
##  7 1420163    26
##  8 1420165    26
##  9 1420169    26
## 10 1420171    26
## # ... with 70 more rows
\end{verbatim}

we have 5 trials repeated during learning four times (20) plus 4
practice trials. How was accuracy distributed across participants?

First, let's consider that when we have a timeout, the output is -1

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{randomDot }\OperatorTok{%>%}\StringTok{                             }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, resp) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(rt }\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 57 x 3
## # Groups:   subjID, resp [57]
##     subjID resp      n
##      <int> <fct> <int>
##  1 1414932 -1       10
##  2 1414933 -1        1
##  3 1414945 -1        3
##  4 1415040 -1        1
##  5 1420163 -1        2
##  6 1420165 -1        1
##  7 1420180 -1        2
##  8 1420185 -1        1
##  9 1420204 -1        1
## 10 1420552 -1        3
## # ... with 47 more rows
\end{verbatim}

Here we can see that some participant missed some trials.

Let's see how accuracy is coded when response is -1:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(randomDot[randomDot}\OperatorTok{$}\NormalTok{rt }\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA NA NA NA NA NA
\end{verbatim}

So it is coded as ``NA'', great. However:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{nrow}\NormalTok{(randomDot[}\KeywordTok{is.na}\NormalTok{(randomDot}\OperatorTok{$}\NormalTok{acc),]) }\CommentTok{#total of NA}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 198
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{nrow}\NormalTok{(randomDot[randomDot}\OperatorTok{$}\NormalTok{resp }\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{,]) }\CommentTok{# total of timeouts}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 127
\end{verbatim}

There are more NA's in acc than can be explained by timeouts. This means
that also wrong responses are coded as NA. We need to recode those.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{randomDot[}\KeywordTok{is.na}\NormalTok{(randomDot}\OperatorTok{$}\NormalTok{acc),]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{0} \CommentTok{#recode everything that is wrong or timeout as 0}
\end{Highlighting}
\end{Shaded}

So, now we can check the overall accuracy of participants, filtering by
timeouts:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID, }\DataTypeTok{data =}\NormalTok{ randomDot[}\OperatorTok{!}\NormalTok{(randomDot}\OperatorTok{$}\NormalTok{resp }\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{),], }\DataTypeTok{FUN =}\NormalTok{ mean)}\CommentTok{# without timeouts}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     subjID       acc
## 1  1414932 0.6875000
## 2  1414933 1.0000000
## 3  1414937 1.0000000
## 4  1414945 1.0000000
## 5  1414957 1.0000000
## 6  1415040 1.0000000
## 7  1420163 0.9583333
## 8  1420165 0.9600000
## 9  1420169 1.0000000
## 10 1420171 1.0000000
## 11 1420177 1.0000000
## 12 1420180 0.9583333
## 13 1420185 1.0000000
## 14 1420199 1.0000000
## 15 1420204 1.0000000
## 16 1420552 1.0000000
## 17 1420573 1.0000000
## 18 1420577 0.9583333
## 19 1420580 1.0000000
## 20 1420622 1.0000000
## 21 1422463 1.0000000
## 22 1422465 1.0000000
## 23 1422466 0.9565217
## 24 1422467 1.0000000
## 25 1422470 0.7600000
## 26 1422472 1.0000000
## 27 1422473 1.0000000
## 28 1422475 0.5200000
## 29 1422476 0.9600000
## 30 1422477 1.0000000
## 31 1422675 1.0000000
## 32 1422676 0.9615385
## 33 1422677 0.9047619
## 34 1422678 0.9600000
## 35 1422679 0.9565217
## 36 1422680 1.0000000
## 37 1422681 1.0000000
## 38 1422689 0.6000000
## 39 1422715 1.0000000
## 40 1422716 1.0000000
## 41 1431942 0.8461538
## 42 1431944 0.7619048
## 43 1431946 1.0000000
## 44 1431948 0.9600000
## 45 1431949 1.0000000
## 46 1431952 0.9565217
## 47 1431953 0.9615385
## 48 1431954 1.0000000
## 49 1431956 0.9166667
## 50 1431957 1.0000000
## 51 1431958 0.9615385
## 52 1431959 1.0000000
## 53 1431960 1.0000000
## 54 1431961 1.0000000
## 55 1431963 1.0000000
## 56 1431965 1.0000000
## 57 1431966 0.9600000
## 58 1431968 1.0000000
## 59 1431969 1.0000000
## 60 1431970 0.9565217
## 61 1431972 0.9600000
## 62 1431974 1.0000000
## 63 1431978 1.0000000
## 64 1431979 1.0000000
## 65 1431981 1.0000000
## 66 1431984 0.9600000
## 67 1431989 1.0000000
## 68 1431992 1.0000000
## 69 1431997 1.0000000
## 70 1431998 1.0000000
## 71 1431999 1.0000000
## 72 1432003 0.9130435
## 73 1432007 1.0000000
## 74 1432009 0.9600000
## 75 1432011 0.9090909
## 76 1432030 1.0000000
## 77 1432052 0.9166667
## 78 1432075 0.9600000
## 79 1432301 1.0000000
## 80 1432323 1.0000000
\end{verbatim}

Now that we have all tests separated, better to remove this file:

\hypertarget{data-visualization}{%
\section{Data visualization}\label{data-visualization}}

\hypertarget{rt}{%
\subsection{rt}\label{rt}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rbind}\NormalTok{(generalizationPL, generalizationLP, contingencyJudgement)->}\StringTok{ }\NormalTok{alltasks}
\NormalTok{alltasks <-}\StringTok{ }\KeywordTok{droplevels}\NormalTok{(alltasks)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{gghistogram}\NormalTok{(alltasks,}
       \DataTypeTok{x =} \StringTok{"rt"}\NormalTok{,}
       \DataTypeTok{y =} \StringTok{"..count.."}\NormalTok{,}
       \DataTypeTok{xlab =} \StringTok{"rt"}\NormalTok{, }
       \DataTypeTok{color =} \StringTok{"task"}\NormalTok{, }
       \DataTypeTok{fill =} \StringTok{"task"}\NormalTok{,}
       \DataTypeTok{palette =} \StringTok{"jco"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `bins = 30` by default. Pick better value with the argument
## `bins`.
\end{verbatim}

\begin{verbatim}
## Warning: Removed 697 rows containing non-finite values (stat_bin).
\end{verbatim}

\includegraphics{preProcessing_files/figure-latex/RT hist-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(alltasks)}
\end{Highlighting}
\end{Shaded}

\hypertarget{accuracy}{%
\subsection{accuracy}\label{accuracy}}

\hypertarget{randomdot}{%
\subsubsection{RandomDot}\label{randomdot}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{unique}\NormalTok{(randomDot}\OperatorTok{$}\NormalTok{subjID)->}\StringTok{ }\NormalTok{subj;}
\NormalTok{randomDot->}\StringTok{ }\NormalTok{randomTask}

\NormalTok{trials <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\StringTok{'0'}\NormalTok{, }\DecValTok{6}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\StringTok{'1'}\NormalTok{, }\DecValTok{5}\NormalTok{), }
              \KeywordTok{rep}\NormalTok{(}\StringTok{'2'}\NormalTok{, }\DecValTok{5}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\StringTok{'3'}\NormalTok{, }\DecValTok{5}\NormalTok{), }
              \KeywordTok{rep}\NormalTok{(}\StringTok{'4'}\NormalTok{, }\DecValTok{5}\NormalTok{))}

\NormalTok{trialstot <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{rep}\NormalTok{(trials, }\KeywordTok{length}\NormalTok{(subj)))}

\NormalTok{randomTask}\OperatorTok{$}\NormalTok{blocks <-}\StringTok{ }\NormalTok{trialstot}
\end{Highlighting}
\end{Shaded}

How many timeouts?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{randomTask}\OperatorTok{$}\NormalTok{timeout <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(randomTask}\OperatorTok{$}\NormalTok{resp}\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{temp<-randomTask }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(timeout, subjID) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(timeout }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{)}

\KeywordTok{unique}\NormalTok{(temp}\OperatorTok{$}\NormalTok{subjID)->}\StringTok{ }\NormalTok{subjs}

\NormalTok{temp2<-randomTask[}\OperatorTok{!}\NormalTok{(randomTask}\OperatorTok{$}\NormalTok{subjID }\OperatorTok{%in%}\StringTok{ }\NormalTok{subjs),] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(timeout, subjID) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(timeout }\OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{)}

\NormalTok{temp2[temp2}\OperatorTok{$}\NormalTok{timeout}\OperatorTok{==}\DecValTok{0}\NormalTok{,]}\OperatorTok{$}\NormalTok{n <-}\StringTok{ }\DecValTok{0}

\KeywordTok{rbind}\NormalTok{(temp,temp2)->}\StringTok{ }\NormalTok{timeout}
\end{Highlighting}
\end{Shaded}

Histogram

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(timeout}\OperatorTok{$}\NormalTok{n, }\DataTypeTok{xlab =} \StringTok{'number of timeouts'}\NormalTok{, }
     \DataTypeTok{main =} \StringTok{''}\NormalTok{, }
     \DataTypeTok{col=}\KeywordTok{grey}\NormalTok{(.}\DecValTok{80}\NormalTok{), }
     \DataTypeTok{border=}\KeywordTok{grey}\NormalTok{(}\DecValTok{0}\NormalTok{),}
     \DataTypeTok{breaks =} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\KeywordTok{max}\NormalTok{(timeout}\OperatorTok{$}\NormalTok{n),}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-32-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timeout <-}\StringTok{ }\NormalTok{randomTask }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, blocks) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(resp }\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{() }


\KeywordTok{ggbarplot}\NormalTok{(timeout[timeout}\OperatorTok{$}\NormalTok{n}\OperatorTok{>}\DecValTok{1}\NormalTok{,], }\DataTypeTok{x =} \StringTok{"blocks"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"n"}\NormalTok{,}
          \DataTypeTok{facet.by =} \StringTok{"subjID"}\NormalTok{,}
          \DataTypeTok{sort.by.groups =} \OtherTok{TRUE}\NormalTok{,     }\CommentTok{# Sort inside each group}
          \DataTypeTok{ylab =} \StringTok{"num of timeouts"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-33-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accdistr <-}\StringTok{ }\NormalTok{randomTask[}\OperatorTok{!}\NormalTok{(randomTask}\OperatorTok{$}\NormalTok{resp }\OperatorTok{==}\StringTok{ }\DecValTok{-1}\NormalTok{),] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(subjID, blocks) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{m =} \KeywordTok{mean}\NormalTok{(acc))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggstripchart}\NormalTok{(accdistr, }\DataTypeTok{x =} \StringTok{"blocks"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"m"}\NormalTok{,}
             \DataTypeTok{xlab =} \StringTok{"blocks"}\NormalTok{,}
             \DataTypeTok{ylab =} \StringTok{"accuracy"}\NormalTok{,}
             \DataTypeTok{add =} \StringTok{"mean_ci"}\NormalTok{,}
             \DataTypeTok{size =} \DecValTok{2}\NormalTok{,}
             \DataTypeTok{color =} \StringTok{"darkgray"}\NormalTok{,}
             \DataTypeTok{shape =} \DecValTok{21}\NormalTok{,}
             \DataTypeTok{fill =} \StringTok{"gray"}\NormalTok{,}
             \DataTypeTok{error.plot =} \StringTok{"pointrange"}\NormalTok{,}
             \DataTypeTok{add.params =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{color =} \StringTok{"black"}\NormalTok{,}
                               \DataTypeTok{size =} \FloatTok{0.7}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\DecValTok{1}\NormalTok{), }\DataTypeTok{oob =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{squish) }\OperatorTok{+}\StringTok{ }\CommentTok{#to prevent jitter to move above 100%}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.50}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-35-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accdistr[accdistr}\OperatorTok{$}\NormalTok{m}\OperatorTok{<}\NormalTok{.}\DecValTok{7}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 13 x 3
## # Groups:   subjID [8]
##     subjID blocks     m
##      <int> <fct>  <dbl>
##  1 1414932 3      0.6  
##  2 1414932 4      0.25 
##  3 1422470 1      0.4  
##  4 1422475 2      0.5  
##  5 1422475 3      0.2  
##  6 1422475 4      0    
##  7 1422689 3      0    
##  8 1422689 4      0.4  
##  9 1431942 4      0.4  
## 10 1431944 1      0.6  
## 11 1431944 3      0.6  
## 12 1431956 4      0.6  
## 13 1432003 0      0.667
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(temp, temp2, timeout, subj, subjs, trials, trialstot, accdistr)}
\end{Highlighting}
\end{Shaded}

\hypertarget{task-1-from-picture-to-labels}{%
\subsubsection{Task 1: from picture to
labels}\label{task-1-from-picture-to-labels}}

The column fribbleID stores the fribble presented, while the column
label stores the labels presented. Resp column in this task refers to
the label selected. Category and frequency refers to the fribbleID
column.

I'm going to add 1 in the accuracy column for every instance where
response matches the category column, i.e., the participant correctly
associated the fribble to its label.

I remove the no-response, and compute accuracy based on category and
response.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationPL}\OperatorTok{$}\NormalTok{subjID))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 80
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fl<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationPL[generalizationPL}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{subjID))}
\NormalTok{lf<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationPL[generalizationPL}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{subjID))}
\end{Highlighting}
\end{Shaded}

We have 41 for feature-label learning, and 39 for label-feature
learning.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{hist}\NormalTok{(generalizationPL[generalizationPL}\OperatorTok{$}\NormalTok{rt}\OperatorTok{<}\DecValTok{600}\NormalTok{,]}\OperatorTok{$}\NormalTok{rt, }\DataTypeTok{main =} \StringTok{'rt < 600ms'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'trials'}\NormalTok{);}
\KeywordTok{hist}\NormalTok{(generalizationPL[generalizationPL}\OperatorTok{$}\NormalTok{rt}\OperatorTok{>}\DecValTok{2000}\NormalTok{,]}\OperatorTok{$}\NormalTok{rt, }\DataTypeTok{main =} \StringTok{'rt > 2000ms'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'trials'}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/hist of rt-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(fl,lf)}
\NormalTok{pictureLabel <-}\StringTok{ }\NormalTok{generalizationPL[}\OperatorTok{!}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(generalizationPL}\OperatorTok{$}\NormalTok{resp)),]}

\NormalTok{pictureLabel}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{0}\NormalTok{;}
\NormalTok{pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{1} \OperatorTok{&}\StringTok{ }\NormalTok{pictureLabel}\OperatorTok{$}\NormalTok{resp}\OperatorTok{==}\StringTok{'dep'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{1}\NormalTok{;}

\NormalTok{pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{2} \OperatorTok{&}\StringTok{ }\NormalTok{pictureLabel}\OperatorTok{$}\NormalTok{resp}\OperatorTok{==}\StringTok{'bim'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{1}\NormalTok{;}

\NormalTok{pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{3} \OperatorTok{&}\StringTok{ }\NormalTok{pictureLabel}\OperatorTok{$}\NormalTok{resp}\OperatorTok{==}\StringTok{'tob'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{1}\NormalTok{;}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(pictureLabel}\OperatorTok{$}\NormalTok{subjID))}
\NormalTok{nrows <-}\StringTok{ }\NormalTok{(}\KeywordTok{nrow}\NormalTok{(generalizationPL)) }\OperatorTok{-}\StringTok{ }\NormalTok{(}\KeywordTok{nrow}\NormalTok{(pictureLabel))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(pictureLabel}\OperatorTok{$}\NormalTok{subjID))->}\StringTok{ }\NormalTok{subjs;}
\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationPL}\OperatorTok{$}\NormalTok{subjID)) ->totsubjs;}

\NormalTok{subjmissed<-}\StringTok{ }\KeywordTok{setdiff}\NormalTok{(totsubjs, subjs);}

\KeywordTok{rm}\NormalTok{(subjs, totsubjs);}
\end{Highlighting}
\end{Shaded}

We have 79 participants in this task, this is -1 compared to our total
number of participants. The subject(s) that didn't answer at all the
task is: 1420171. We have lost also 136 responses, that is 7.0833333
over the total: 1920.

Calculate the proportion of correct in each condition:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(n, subjmissed, nrows)}

\NormalTok{ss_prop<-}\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{frequency}\OperatorTok{+}\NormalTok{category}\OperatorTok{+}\NormalTok{subjID}\OperatorTok{+}\NormalTok{learning, }
                   \DataTypeTok{data =}\NormalTok{ pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], }\DataTypeTok{FUN =}\NormalTok{ mean)}
\end{Highlighting}
\end{Shaded}

Plot aggregated over subjs. To see accuracy distributed over categories.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\NormalTok{ss_prop }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{( category, frequency, learning) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n=}\KeywordTok{n}\NormalTok{(),}
    \DataTypeTok{mean=}\KeywordTok{mean}\NormalTok{(acc),}
    \DataTypeTok{sd=}\KeywordTok{sd}\NormalTok{(acc)}
\NormalTok{  ) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{se=}\NormalTok{sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{ci=}\NormalTok{se }\OperatorTok{*}\StringTok{ }\KeywordTok{qt}\NormalTok{((}\DecValTok{1}\FloatTok{-0.05}\NormalTok{)}\OperatorTok{/}\DecValTok{2} \OperatorTok{+}\StringTok{ }\FloatTok{.5}\NormalTok{, n}\DecValTok{-1}\NormalTok{))}

\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ category, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill =}\NormalTok{ frequency), }\DataTypeTok{data =}\NormalTok{ ms) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{color=}\StringTok{'white'}\NormalTok{, }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(), }\DataTypeTok{size=}\FloatTok{1.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_errorbar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{ymin=}\NormalTok{mean}\OperatorTok{-}\NormalTok{se, }\DataTypeTok{ymax=}\NormalTok{mean}\OperatorTok{+}\NormalTok{se), }\DataTypeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\DataTypeTok{size=}\DecValTok{1}\NormalTok{,}\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(.}\DecValTok{9}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Accuracy "}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"category"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'pictureLabels'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggpubr}\OperatorTok{::}\KeywordTok{theme_pubclean}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{legend.title =} \KeywordTok{element_blank}\NormalTok{()) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size=}\DecValTok{10}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-38-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning}\OperatorTok{+}\NormalTok{category, }
                \DataTypeTok{data =}\NormalTok{ pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], mean)}
\NormalTok{df}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggviolin}\NormalTok{(df, }\DataTypeTok{x =} \StringTok{"frequency"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"acc"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"frequency"}\NormalTok{,}
         \DataTypeTok{palette =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{),}
         \DataTypeTok{add =} \StringTok{"boxplot"}\NormalTok{, }
         \DataTypeTok{add.params =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{),}
         \DataTypeTok{trim=}\OtherTok{TRUE}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'pictureLabels'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{facet_grid}\NormalTok{( learning }\OperatorTok{~}\StringTok{ }\NormalTok{category) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_pubclean}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-39-1.pdf}

Let's see how participants scored for the high/low frequency:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning, }
                \DataTypeTok{data =}\NormalTok{ pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], mean)}
\NormalTok{df}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggviolin}\NormalTok{(df, }\DataTypeTok{x =} \StringTok{"frequency"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"acc"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"frequency"}\NormalTok{,}
         \DataTypeTok{palette =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{),}
         \DataTypeTok{add =} \StringTok{"boxplot"}\NormalTok{, }
         \DataTypeTok{add.params =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{),}
         \DataTypeTok{trim=}\OtherTok{TRUE}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'pictureLabels'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_pubclean}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-40-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{hist}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'low'} \OperatorTok{&}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'low freq - FL '}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'low'} \OperatorTok{&}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'low freq - LF '}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'high'} \OperatorTok{&}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'high freq - FL '}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'high'} \OperatorTok{&}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'high freq - LF '}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-41-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#barPlot aggregated over categories:}

\NormalTok{ms <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning, }
                \DataTypeTok{data=}\NormalTok{pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], }\DataTypeTok{FUN=}\NormalTok{ mean)}

\NormalTok{df<-}\StringTok{ }\NormalTok{ms }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(frequency, learning)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}
    \DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(acc),}
    \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(acc),}
    \DataTypeTok{n =} \KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{se=}\NormalTok{sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{ci=}\NormalTok{se }\OperatorTok{*}\StringTok{ }\KeywordTok{qt}\NormalTok{((}\DecValTok{1}\FloatTok{-0.05}\NormalTok{)}\OperatorTok{/}\DecValTok{2} \OperatorTok{+}\StringTok{ }\FloatTok{.5}\NormalTok{, n}\DecValTok{-1}\NormalTok{))}

\NormalTok{df}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}


\NormalTok{pl<-}\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ frequency, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill =}\NormalTok{ frequency), }\DataTypeTok{data =}\NormalTok{ df) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{color=}\StringTok{'white'}\NormalTok{, }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(), }\DataTypeTok{size=}\FloatTok{1.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_errorbar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{ymin=}\NormalTok{mean}\OperatorTok{-}\NormalTok{se, }\DataTypeTok{ymax=}\NormalTok{mean}\OperatorTok{+}\NormalTok{se), }\DataTypeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\DataTypeTok{size=}\DecValTok{1}\NormalTok{,}\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(.}\DecValTok{9}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Accuracy "}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"frequency"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'pictureLabels'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggpubr}\OperatorTok{::}\KeywordTok{theme_pubclean}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{legend.title =} \KeywordTok{element_blank}\NormalTok{()) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size=}\DecValTok{10}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\hypertarget{task-2-from-label-to-pictures}{%
\subsubsection{Task 2: from label to
pictures}\label{task-2-from-label-to-pictures}}

Let's check now the generalizaton from label to pictures:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{subjID))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 80
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fl<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{subjID))}
\NormalTok{lf<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{subjID))}
\end{Highlighting}
\end{Shaded}

We have 41 for feature-label learning, and 39 for label-feature
learning.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(fl,lf)}
\NormalTok{labelPicture <-}\StringTok{ }\NormalTok{generalizationLP[}\OperatorTok{!}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{resp)),]}
\NormalTok{n<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(labelPicture}\OperatorTok{$}\NormalTok{subjID))}
\NormalTok{nrows <-}\StringTok{ }\NormalTok{(}\KeywordTok{nrow}\NormalTok{(generalizationLP)) }\OperatorTok{-}\StringTok{ }\NormalTok{(}\KeywordTok{nrow}\NormalTok{(labelPicture))}

\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(labelPicture}\OperatorTok{$}\NormalTok{subjID))->}\StringTok{ }\NormalTok{subjs;}
\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(generalizationLP}\OperatorTok{$}\NormalTok{subjID)) ->totsubjs;}

\NormalTok{subjmissed<-}\StringTok{ }\KeywordTok{setdiff}\NormalTok{(totsubjs, subjs);}
\end{Highlighting}
\end{Shaded}

Great, we have 80 participants in this task, so -0, and we have missed
179 over the total 1920, that is 9.3229167. The subject(s) that missed
completely the task is: .

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{hist}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{rt}\OperatorTok{<}\DecValTok{600}\NormalTok{,]}\OperatorTok{$}\NormalTok{rt, }\DataTypeTok{main =} \StringTok{'rt < 600ms'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'trials'}\NormalTok{);}
\KeywordTok{hist}\NormalTok{(generalizationLP[generalizationLP}\OperatorTok{$}\NormalTok{rt}\OperatorTok{>}\DecValTok{2000}\NormalTok{,]}\OperatorTok{$}\NormalTok{rt, }\DataTypeTok{main =} \StringTok{'rt > 2000ms'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'trials'}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-45-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(n, nrows, subjs, totsubjs);}
\NormalTok{labelPicture}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{0}\NormalTok{;}
\NormalTok{labelPicture[labelPicture}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{1} \OperatorTok{&}\StringTok{ }\NormalTok{labelPicture}\OperatorTok{$}\NormalTok{label}\OperatorTok{==}\StringTok{'dep'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{1}\NormalTok{;}
\NormalTok{labelPicture[labelPicture}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{2} \OperatorTok{&}\StringTok{ }\NormalTok{labelPicture}\OperatorTok{$}\NormalTok{label}\OperatorTok{==}\StringTok{'bim'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{1}\NormalTok{;}
\NormalTok{labelPicture[labelPicture}\OperatorTok{$}\NormalTok{category}\OperatorTok{==}\DecValTok{3} \OperatorTok{&}\StringTok{ }\NormalTok{labelPicture}\OperatorTok{$}\NormalTok{label}\OperatorTok{==}\StringTok{'tob'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc <-}\StringTok{ }\DecValTok{1}\NormalTok{;}
\end{Highlighting}
\end{Shaded}

Calculate the proportion of correct in each condition

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(subjmissed)}
\NormalTok{ss_prop<-}\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{frequency}\OperatorTok{+}\NormalTok{category}\OperatorTok{+}\NormalTok{subjID}\OperatorTok{+}\NormalTok{learning, }
                   \DataTypeTok{data =}\NormalTok{ labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,], }\DataTypeTok{FUN =}\NormalTok{ mean)}
\end{Highlighting}
\end{Shaded}

Plot aggregated over subjs. To see accuracy distributed over categories.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\NormalTok{ss_prop }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(category, frequency, learning) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}
    \DataTypeTok{n=}\KeywordTok{n}\NormalTok{(),}
    \DataTypeTok{mean=}\KeywordTok{mean}\NormalTok{(acc),}
    \DataTypeTok{sd=}\KeywordTok{sd}\NormalTok{(acc)}
\NormalTok{  ) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{se=}\NormalTok{sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{ci=}\NormalTok{se }\OperatorTok{*}\StringTok{ }\KeywordTok{qt}\NormalTok{((}\DecValTok{1}\FloatTok{-0.05}\NormalTok{)}\OperatorTok{/}\DecValTok{2} \OperatorTok{+}\StringTok{ }\FloatTok{.5}\NormalTok{, n}\DecValTok{-1}\NormalTok{))}

\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ category, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill =}\NormalTok{ frequency), }\DataTypeTok{data =}\NormalTok{ ms) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{color=}\StringTok{'white'}\NormalTok{, }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(), }\DataTypeTok{size=}\FloatTok{1.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_errorbar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{ymin=}\NormalTok{mean}\OperatorTok{-}\NormalTok{se, }\DataTypeTok{ymax=}\NormalTok{mean}\OperatorTok{+}\NormalTok{se), }\DataTypeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\DataTypeTok{size=}\DecValTok{1}\NormalTok{,}\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(.}\DecValTok{9}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Accuracy "}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"category"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'labelPictures'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggpubr}\OperatorTok{::}\KeywordTok{theme_pubclean}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{legend.title =} \KeywordTok{element_blank}\NormalTok{()) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size=}\DecValTok{10}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-48-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning}\OperatorTok{+}\NormalTok{category, }
                \DataTypeTok{data =}\NormalTok{ labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], mean)}

\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggviolin}\NormalTok{(ms, }\DataTypeTok{x =} \StringTok{"frequency"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"acc"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"frequency"}\NormalTok{,}
         \DataTypeTok{palette =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{),}
         \DataTypeTok{add =} \StringTok{"boxplot"}\NormalTok{, }
         \DataTypeTok{add.params =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{),}
         \DataTypeTok{trim=}\OtherTok{TRUE}\NormalTok{) }\OperatorTok{+}
\StringTok{         }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'labelPictures'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{facet_grid}\NormalTok{( learning }\OperatorTok{~}\StringTok{ }\NormalTok{category) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_pubclean}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-49-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#rm(ms, ss_prop)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning, }
                \DataTypeTok{data =}\NormalTok{ labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], mean)}

\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggviolin}\NormalTok{(ms, }\DataTypeTok{x =} \StringTok{"frequency"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"acc"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"frequency"}\NormalTok{,}
         \DataTypeTok{palette =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{),}
         \DataTypeTok{add =} \StringTok{"boxplot"}\NormalTok{, }
         \DataTypeTok{add.params =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{),}
         \DataTypeTok{trim=}\OtherTok{TRUE}\NormalTok{) }\OperatorTok{+}
\StringTok{         }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'labelPictures'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_pubclean}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-50-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#rm(ms, ss_prop)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{hist}\NormalTok{(ms[ms}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'low'} \OperatorTok{&}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'low freq - FL '}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(ms[ms}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'low'} \OperatorTok{&}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'low freq - LF '}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(ms[ms}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'high'} \OperatorTok{&}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'high freq - FL '}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(ms[ms}\OperatorTok{$}\NormalTok{frequency}\OperatorTok{==}\StringTok{'high'} \OperatorTok{&}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{acc, }\DataTypeTok{xlab =} \StringTok{'acc'}\NormalTok{, }\DataTypeTok{main =} \StringTok{'high freq - LF '}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-51-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{comparison-by-learning-by-tasks}{%
\subsubsection{Comparison by learning by
tasks}\label{comparison-by-learning-by-tasks}}

Inspection of the speed-accuracy trade-off:

labelPicture

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rt_range <-}\StringTok{ }\DecValTok{2500}
\NormalTok{n_bins <-}\StringTok{ }\DecValTok{10}
\NormalTok{break_seq <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, rt_range, rt_range}\OperatorTok{/}\NormalTok{n_bins)}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(learning }\OperatorTok{==}\StringTok{ "FL"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin =} \KeywordTok{cut}\NormalTok{(rt, }\DataTypeTok{breaks =}\NormalTok{ break_seq)) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin_avg =} \KeywordTok{mean}\NormalTok{(rt, }\DataTypeTok{na.rm =}\NormalTok{ T))}

\NormalTok{count_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{subjcount =} \KeywordTok{n_distinct}\NormalTok{(subjID), }\DataTypeTok{totalcount =} \KeywordTok{n}\NormalTok{())}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category, subjID) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{ss_acc =} \KeywordTok{mean}\NormalTok{(acc, }\DataTypeTok{na.rm=}\NormalTok{T)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(ss_acc),}
            \DataTypeTok{n =} \KeywordTok{n}\NormalTok{())}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{RT_bin_avg, }\DataTypeTok{y=}\NormalTok{mean, }\DataTypeTok{weight =}\NormalTok{ n), }
           \DataTypeTok{data =}\NormalTok{ timeslice_range) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{size =}\NormalTok{ n), }\DataTypeTok{shape =} \DecValTok{21}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{stroke =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{formula =}\NormalTok{ y }\OperatorTok{~}\StringTok{ }\KeywordTok{poly}\NormalTok{(x,}\DecValTok{2}\NormalTok{), }\DataTypeTok{se =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{color =} \StringTok{"#0892d0"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"lightgray"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.5}\NormalTok{, }\DataTypeTok{lty =} \StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggthemes}\OperatorTok{::}\KeywordTok{theme_hc}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Average RT on trials"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'speed-accuracy tradeoff - FL - labelPicture'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-52-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
  \KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion Correct"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $y
## [1] "Proportion Correct"
## 
## attr(,"class")
## [1] "labels"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rt_range <-}\StringTok{ }\DecValTok{2500}
\NormalTok{n_bins <-}\StringTok{ }\DecValTok{10}
\NormalTok{break_seq <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, rt_range, rt_range}\OperatorTok{/}\NormalTok{n_bins)}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(learning }\OperatorTok{==}\StringTok{ "LF"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin =} \KeywordTok{cut}\NormalTok{(rt, }\DataTypeTok{breaks =}\NormalTok{ break_seq)) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin_avg =} \KeywordTok{mean}\NormalTok{(rt, }\DataTypeTok{na.rm =}\NormalTok{ T))}

\NormalTok{count_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{subjcount =} \KeywordTok{n_distinct}\NormalTok{(subjID), }\DataTypeTok{totalcount =} \KeywordTok{n}\NormalTok{())}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category, subjID) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{ss_acc =} \KeywordTok{mean}\NormalTok{(acc, }\DataTypeTok{na.rm=}\NormalTok{T)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(ss_acc),}
            \DataTypeTok{n =} \KeywordTok{n}\NormalTok{())}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{RT_bin_avg, }\DataTypeTok{y=}\NormalTok{mean, }\DataTypeTok{weight =}\NormalTok{ n), }
           \DataTypeTok{data =}\NormalTok{ timeslice_range) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{size =}\NormalTok{ n), }\DataTypeTok{shape =} \DecValTok{21}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{stroke =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{formula =}\NormalTok{ y }\OperatorTok{~}\StringTok{ }\KeywordTok{poly}\NormalTok{(x,}\DecValTok{2}\NormalTok{), }\DataTypeTok{se =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{color =} \StringTok{"#0892d0"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"lightgray"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.5}\NormalTok{, }\DataTypeTok{lty =} \StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggthemes}\OperatorTok{::}\KeywordTok{theme_hc}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Average RT on trials"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'speed-accuracy tradeoff LF - LabelPicture'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-53-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
  \KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion Correct"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $y
## [1] "Proportion Correct"
## 
## attr(,"class")
## [1] "labels"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{learning, labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,], mean)->}\StringTok{ }\NormalTok{speedacc}
\KeywordTok{aggregate}\NormalTok{(rt }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{learning, labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], mean)->}\StringTok{ }\NormalTok{speedacc2}
\KeywordTok{merge}\NormalTok{(speedacc, speedacc2, }\DataTypeTok{by =}  \KeywordTok{c}\NormalTok{(}\StringTok{"subjID"}\NormalTok{, }\StringTok{"learning"}\NormalTok{))->}\StringTok{ }\NormalTok{speedacc}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{rt, }\DataTypeTok{y=}\NormalTok{acc), }
           \DataTypeTok{data =}\NormalTok{ speedacc) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{( }\DataTypeTok{shape =} \DecValTok{21}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{3}\NormalTok{, }\DataTypeTok{stroke =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\CommentTok{#geom_smooth(method = "lm", formula = y ~ poly(x,2), se = TRUE, color = "#0892d0", fill = "lightgray") +}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.33}\NormalTok{, }\DataTypeTok{lty =} \StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggthemes}\OperatorTok{::}\KeywordTok{theme_hc}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Average RT on subjs"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion Correct"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"speed-acc tradeoff - labelPicture"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-54-1.pdf}

PictureLabel:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rt_range <-}\StringTok{ }\DecValTok{2500}
\NormalTok{n_bins <-}\StringTok{ }\DecValTok{10}
\NormalTok{break_seq <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, rt_range, rt_range}\OperatorTok{/}\NormalTok{n_bins)}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(learning }\OperatorTok{==}\StringTok{ "FL"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin =} \KeywordTok{cut}\NormalTok{(rt, }\DataTypeTok{breaks =}\NormalTok{ break_seq)) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin_avg =} \KeywordTok{mean}\NormalTok{(rt, }\DataTypeTok{na.rm =}\NormalTok{ T))}

\NormalTok{count_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{subjcount =} \KeywordTok{n_distinct}\NormalTok{(subjID), }\DataTypeTok{totalcount =} \KeywordTok{n}\NormalTok{())}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category, subjID) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{ss_acc =} \KeywordTok{mean}\NormalTok{(acc, }\DataTypeTok{na.rm=}\NormalTok{T)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(ss_acc),}
            \DataTypeTok{n =} \KeywordTok{n}\NormalTok{())}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{RT_bin_avg, }\DataTypeTok{y=}\NormalTok{mean, }\DataTypeTok{weight =}\NormalTok{ n), }
           \DataTypeTok{data =}\NormalTok{ timeslice_range) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{size =}\NormalTok{ n), }\DataTypeTok{shape =} \DecValTok{21}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{stroke =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{formula =}\NormalTok{ y }\OperatorTok{~}\StringTok{ }\KeywordTok{poly}\NormalTok{(x,}\DecValTok{2}\NormalTok{), }\DataTypeTok{se =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{color =} \StringTok{"#0892d0"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"lightgray"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.5}\NormalTok{, }\DataTypeTok{lty =} \StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggthemes}\OperatorTok{::}\KeywordTok{theme_hc}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Average RT on trials"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'speed-accuracy tradeoff - FL - pictureLabel'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-55-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
  \KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion Correct"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $y
## [1] "Proportion Correct"
## 
## attr(,"class")
## [1] "labels"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rt_range <-}\StringTok{ }\DecValTok{2500}
\NormalTok{n_bins <-}\StringTok{ }\DecValTok{10}
\NormalTok{break_seq <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, rt_range, rt_range}\OperatorTok{/}\NormalTok{n_bins)}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(learning }\OperatorTok{==}\StringTok{ "LF"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin =} \KeywordTok{cut}\NormalTok{(rt, }\DataTypeTok{breaks =}\NormalTok{ break_seq)) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{RT_bin_avg =} \KeywordTok{mean}\NormalTok{(rt, }\DataTypeTok{na.rm =}\NormalTok{ T))}

\NormalTok{count_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(RT_bin, category) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{subjcount =} \KeywordTok{n_distinct}\NormalTok{(subjID), }\DataTypeTok{totalcount =} \KeywordTok{n}\NormalTok{())}

\NormalTok{timeslice_range <-}\StringTok{ }\NormalTok{timeslice_range }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category, subjID) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{ss_acc =} \KeywordTok{mean}\NormalTok{(acc, }\DataTypeTok{na.rm=}\NormalTok{T)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{group_by}\NormalTok{(RT_bin_avg, category) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(ss_acc),}
            \DataTypeTok{n =} \KeywordTok{n}\NormalTok{())}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{RT_bin_avg, }\DataTypeTok{y=}\NormalTok{mean, }\DataTypeTok{weight =}\NormalTok{ n), }
           \DataTypeTok{data =}\NormalTok{ timeslice_range) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{size =}\NormalTok{ n), }\DataTypeTok{shape =} \DecValTok{21}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{stroke =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{formula =}\NormalTok{ y }\OperatorTok{~}\StringTok{ }\KeywordTok{poly}\NormalTok{(x,}\DecValTok{2}\NormalTok{), }\DataTypeTok{se =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{color =} \StringTok{"#0892d0"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"lightgray"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.5}\NormalTok{, }\DataTypeTok{lty =} \StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggthemes}\OperatorTok{::}\KeywordTok{theme_hc}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Average RT on trials"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'speed-accuracy tradeoff - LF - pictureLabel'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-56-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
  \KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion Correct"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $y
## [1] "Proportion Correct"
## 
## attr(,"class")
## [1] "labels"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{learning, pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{ ,], mean)->}\StringTok{ }\NormalTok{speedacc}
\KeywordTok{aggregate}\NormalTok{(rt }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{learning, pictureLabel[pictureLabel}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], mean)->}\StringTok{ }\NormalTok{speedacc2}
\KeywordTok{merge}\NormalTok{(speedacc, speedacc2, }\DataTypeTok{by =}  \KeywordTok{c}\NormalTok{(}\StringTok{"subjID"}\NormalTok{, }\StringTok{"learning"}\NormalTok{))->}\StringTok{ }\NormalTok{speedacc}

\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{rt, }\DataTypeTok{y=}\NormalTok{acc), }
           \DataTypeTok{data =}\NormalTok{ speedacc) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{( }\DataTypeTok{shape =} \DecValTok{21}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{3}\NormalTok{, }\DataTypeTok{stroke =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\CommentTok{#geom_smooth(method = "lm", formula = y ~ poly(x,2), se = TRUE, color = "#0892d0", fill = "lightgray") +}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.33}\NormalTok{, }\DataTypeTok{lty =} \StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggthemes}\OperatorTok{::}\KeywordTok{theme_hc}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Average RT on subjs"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion Correct"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"speed-acc tradeoff - pictureLabel"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-57-1.pdf}

\hypertarget{comparisons-by-tasks-learning-frequency}{%
\subsubsection{Comparisons by tasks + learning +
frequency}\label{comparisons-by-tasks-learning-frequency}}

Barplot labelPicture

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning, }
                \DataTypeTok{data=}\NormalTok{labelPicture[labelPicture}\OperatorTok{$}\NormalTok{rt }\OperatorTok{>}\StringTok{ }\DecValTok{200}\NormalTok{,], }\DataTypeTok{FUN=}\NormalTok{ mean)}

\NormalTok{df<-}\StringTok{ }\NormalTok{ms }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(frequency, learning)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}
    \DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(acc),}
    \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(acc),}
    \DataTypeTok{n =} \KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{se=}\NormalTok{sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{ci=}\NormalTok{se }\OperatorTok{*}\StringTok{ }\KeywordTok{qt}\NormalTok{((}\DecValTok{1}\FloatTok{-0.05}\NormalTok{)}\OperatorTok{/}\DecValTok{2} \OperatorTok{+}\StringTok{ }\FloatTok{.5}\NormalTok{, n}\DecValTok{-1}\NormalTok{))}

\NormalTok{df}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}


\NormalTok{lp<-}\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ frequency, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill =}\NormalTok{ frequency), }\DataTypeTok{data =}\NormalTok{ df) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{color=}\StringTok{'white'}\NormalTok{, }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(), }\DataTypeTok{size=}\FloatTok{1.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_errorbar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{ymin=}\NormalTok{mean}\OperatorTok{-}\NormalTok{se, }\DataTypeTok{ymax=}\NormalTok{mean}\OperatorTok{+}\NormalTok{se), }\DataTypeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\DataTypeTok{size=}\DecValTok{1}\NormalTok{,}\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(.}\DecValTok{9}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Accuracy "}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"frequency"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"labelPictures"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggpubr}\OperatorTok{::}\KeywordTok{theme_pubclean}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{legend.title =} \KeywordTok{element_blank}\NormalTok{()) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size=}\DecValTok{10}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{grid.arrange}\NormalTok{(lp, pl, }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-59-1.pdf}

Barplots + violinPlots with data from both tasks:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(ms, lp, pl, df, ss_prop)}
\NormalTok{genTask <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(labelPicture, pictureLabel)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning, }\DataTypeTok{data =}\NormalTok{ genTask, mean)}

\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(ms}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{ms}\OperatorTok{$}\NormalTok{frequency;}

\KeywordTok{ggviolin}\NormalTok{(ms, }\DataTypeTok{x =} \StringTok{"frequency"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"acc"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"frequency"}\NormalTok{,}
         \DataTypeTok{palette =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{),}
         \DataTypeTok{add =} \StringTok{"boxplot"}\NormalTok{, }
         \DataTypeTok{add.params =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"white"}\NormalTok{),}
         \DataTypeTok{trim=}\OtherTok{TRUE}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'labelPictures + pictureLabels'}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{        }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_pubclean}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-61-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(acc }\OperatorTok{~}\StringTok{ }\NormalTok{subjID}\OperatorTok{+}\NormalTok{frequency}\OperatorTok{+}\NormalTok{learning, }\DataTypeTok{data=}\NormalTok{genTask, }\DataTypeTok{FUN=}\NormalTok{ mean)}

\NormalTok{df<-}\StringTok{ }\NormalTok{ms }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(frequency, learning)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}
    \DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(acc),}
    \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(acc),}
    \DataTypeTok{n =} \KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{se=}\NormalTok{sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{ci=}\NormalTok{se }\OperatorTok{*}\StringTok{ }\KeywordTok{qt}\NormalTok{((}\DecValTok{1}\FloatTok{-0.05}\NormalTok{)}\OperatorTok{/}\DecValTok{2} \OperatorTok{+}\StringTok{ }\FloatTok{.5}\NormalTok{, n}\DecValTok{-1}\NormalTok{))}

\NormalTok{df}\OperatorTok{$}\NormalTok{frequency <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency)}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"25"}\NormalTok{=}\StringTok{"low"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}
\NormalTok{plyr}\OperatorTok{::}\KeywordTok{revalue}\NormalTok{(df}\OperatorTok{$}\NormalTok{frequency, }\KeywordTok{c}\NormalTok{(}\StringTok{"75"}\NormalTok{=}\StringTok{"high"}\NormalTok{))->}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{frequency;}


\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ frequency, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill =}\NormalTok{ frequency), }\DataTypeTok{data =}\NormalTok{ df) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{( . }\OperatorTok{~}\StringTok{ }\NormalTok{learning) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{color=}\StringTok{'white'}\NormalTok{, }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(), }\DataTypeTok{size=}\FloatTok{1.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_errorbar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{ymin=}\NormalTok{mean}\OperatorTok{-}\NormalTok{se, }\DataTypeTok{ymax=}\NormalTok{mean}\OperatorTok{+}\NormalTok{se), }\DataTypeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\DataTypeTok{size=}\DecValTok{1}\NormalTok{,}\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(.}\DecValTok{9}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Accuracy "}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"frequency"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"labelPicture"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'picturelabels + labelpictures'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\NormalTok{ggpubr}\OperatorTok{::}\KeywordTok{theme_pubclean}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{legend.title =} \KeywordTok{element_blank}\NormalTok{()) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size=}\DecValTok{10}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{.33}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-62-1.pdf}

\hypertarget{task-3-contingency-judgement}{%
\subsubsection{Task 3: Contingency
judgement}\label{task-3-contingency-judgement}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(contingencyJudgement}\OperatorTok{$}\NormalTok{subjID))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 80
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fl<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(contingencyJudgement[contingencyJudgement}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'FL'}\NormalTok{,]}\OperatorTok{$}\NormalTok{subjID))}
\NormalTok{lf<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(contingencyJudgement[contingencyJudgement}\OperatorTok{$}\NormalTok{learning}\OperatorTok{==}\StringTok{'LF'}\NormalTok{,]}\OperatorTok{$}\NormalTok{subjID))}
\end{Highlighting}
\end{Shaded}

We have 41 for feature-label learning, and 39 for label-feature
learning.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(fl,lf)}
\NormalTok{conjudge <-}\StringTok{ }\NormalTok{contingencyJudgement[}\OperatorTok{!}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(contingencyJudgement}\OperatorTok{$}\NormalTok{resp)),]}
\NormalTok{n<-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(conjudge}\OperatorTok{$}\NormalTok{subjID))}
\NormalTok{nrows <-}\StringTok{ }\NormalTok{(}\KeywordTok{nrow}\NormalTok{(contingencyJudgement)) }\OperatorTok{-}\StringTok{ }\NormalTok{(}\KeywordTok{nrow}\NormalTok{(conjudge))}

\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(conjudge}\OperatorTok{$}\NormalTok{subjID))->}\StringTok{ }\NormalTok{subjs;}
\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(contingencyJudgement}\OperatorTok{$}\NormalTok{subjID)) ->totsubjs;}

\NormalTok{subjmissed<-}\StringTok{ }\KeywordTok{setdiff}\NormalTok{(totsubjs, subjs);}
\end{Highlighting}
\end{Shaded}

We have 74 participants in this task, so -6, and we have missed 382 over
the total 1920, that is 19.8958333. The subject(s) that missed
completely the task is/are: 1414932, 1420171, 1420199, 1422475, 1431960,
1431997.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{hist}\NormalTok{(conjudge[conjudge}\OperatorTok{$}\NormalTok{rt}\OperatorTok{<}\DecValTok{1500}\NormalTok{,]}\OperatorTok{$}\NormalTok{rt, }\DataTypeTok{main =} \StringTok{'rt < 1500ms'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'trials'}\NormalTok{);}
\KeywordTok{hist}\NormalTok{(conjudge[conjudge}\OperatorTok{$}\NormalTok{rt}\OperatorTok{>}\DecValTok{3000}\NormalTok{,]}\OperatorTok{$}\NormalTok{rt, }\DataTypeTok{main =} \StringTok{'rt > 3000ms'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'trials'}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/unnamed-chunk-65-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Resp is coded as factor, need to correct this:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{levels}\NormalTok{(conjudge}\OperatorTok{$}\NormalTok{resp))[conjudge}\OperatorTok{$}\NormalTok{resp]->}\StringTok{ }\NormalTok{conjudge}\OperatorTok{$}\NormalTok{resp}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(conjudge}\OperatorTok{$}\NormalTok{resp, }\DataTypeTok{main =} \StringTok{'resp distribution'}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{'choices'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{preProcessing_files/figure-latex/histogram-1.pdf}

Ok, here we don't have right or wrong answers, but we are more
interested in take a look how the participants rated the fribble label
association:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(resp }\OperatorTok{~}\StringTok{ }\NormalTok{category, }\DataTypeTok{data =}\NormalTok{ conjudge, }\DataTypeTok{FUN =}\NormalTok{ mean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   category      resp
## 1        1 -12.52183
## 2        2  -5.50000
## 3        3 -10.09728
\end{verbatim}

\end{document}
